flags:
  QuickCheck:
    base4point8: false
packages:
- '.'
- sql-fragment
extra-deps:
- HList-0.3.4.1
- HUnit-1.3.1.1
- OneTuple-0.2.1
- QuickCheck-2.8.2
- StateVar-1.1.0.1
- adjunctions-4.3
- ansi-terminal-0.6.2.3
- async-2.1.0
- attoparsec-0.13.0.1
- base-orphans-0.5.3
- base16-bytestring-0.1.1.6
- bifunctors-5.2
- blaze-builder-0.4.0.1
- blaze-textual-0.2.1.0
- comonad-4.2.7.2
- contravariant-1.3.3
- dimensional-0.13.0.2
- distributive-0.5.0.2
- doctest-0.10.1
- exceptions-0.8.0.2
- free-4.12.1
- ghc-paths-0.1.0.9
- hashable-1.2.4.0
- hspec-2.2.2
- hspec-core-2.2.2
- hspec-discover-2.2.2
- hspec-expectations-0.7.2
- kan-extensions-5.0.1
- lens-4.13.2.1
- mysql-0.1.1.8
- mysql-simple-0.2.2.5
- nats-1
- numtype-1.1
- parallel-3.2.1.0
- pcre-light-0.4.0.4
- prelude-extras-0.4.0.2
- primitive-0.6.1.0
- profunctors-5.2
- quickcheck-io-0.1.2
- reflection-2.1.2
- regex-base-0.93.2
- regex-pcre-0.94.4
- scientific-0.3.4.6
- semigroupoids-5.0.1
- semigroups-0.17.0.1
- setenv-0.1.1.3
- split-0.2.3
- stm-2.4.4.1
- syb-0.6
- tagged-0.7.3
- text-1.2.2.1
- tf-random-0.5
- transformers-compat-0.4.0.3
- tuple-hlist-0.2.0.1
- unordered-containers-0.2.7.0
- vector-0.11.0.0
- void-0.7.1
resolver: ghc-7.8.4
