flags: {}
packages:
- '.'
- ../sql-fragment
extra-deps:
- HList-0.3.4.1
- OneTuple-0.2.1
- StateVar-1.1.0.1
- ansi-terminal-0.6.2.3
- base16-bytestring-0.1.1.6
- bifunctors-4.2.1
- blaze-builder-0.4.0.1
- blaze-textual-0.2.1.0
- comonad-4.2.7.2
- contravariant-1.3.3
- dimensional-0.13.0.2
- distributive-0.4.4
- doctest-0.10.1
- exceptions-0.8.0.2
- free-4.12.1
- ghc-paths-0.1.0.9
- hspec-2.2.0
- hspec-core-2.2.0
- hspec-discover-2.2.0
- hspec-expectations-0.7.2
- lens-4.4.0.2
- mysql-0.1.1.8
- mysql-simple-0.2.2.5
- nats-1
- numtype-1.1
- pcre-light-0.4.0.4
- prelude-extras-0.4.0.2
- profunctors-4.4.1
- quickcheck-io-0.1.2
- reflection-1.5.2.1
- regex-pcre-0.94.4
- semigroupoids-4.3
- semigroups-0.17.0.1
- setenv-0.1.1.3
- tagged-0.7.3
- tf-random-0.5
- transformers-compat-0.4.0.3
- tuple-hlist-0.2.0.1
- void-0.7.1
resolver: ghc-7.8.3
